services:
  - type: web
    name: golf-swing-ai-optimized
    env: python
    plan: free  # 512MB RAM limit
    buildCommand: "pip install -r requirements_lightweight.txt"
    startCommand: "python api_lightweight.py"
    healthCheckPath: "/health"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: "."
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "1"  # Single worker for memory optimization