import Foundation

// MARK: - Golf Course Data

struct GolfCourse: Identifiable, Sendable {
    let id = UUID()
    let name: String
    let location: String
    let country: String
    /// Per-hole par values (18 elements for a standard course).
    /// Entries marked "verified" use confirmed hole-by-hole data.
    /// All others use a standard distribution for the correct total par
    /// (e.g. par 72 → 4×par-3, 10×par-4, 4×par-5) which the user can
    /// adjust via the Edit button in Par Setup.
    var holePars: [Int]? = nil

    var displayName: String { name }
    var fullDisplay: String { "\(name) – \(location)" }
}

// MARK: - Courses Database

enum GolfCoursesDatabase {

    // ── Standard par distributions ────────────────────────────────────────
    // Used for courses where we know the total par but not every specific hole.
    // Layout legend:  3=par-3, 4=par-4, 5=par-5
    //   par 68 → 4×3, 14×4          (F:33 B:35)
    //   par 69 → 5×3, 11×4, 2×5     (F:33 B:36)
    //   par 70 → 4×3, 12×4, 2×5     (F:35 B:35)
    //   par 71 → 4×3, 11×4, 3×5     (F:36 B:35)
    //   par 72 → 4×3, 10×4, 4×5     (F:36 B:36)  symmetric layout
    //   par 73 → 4×3,  9×4, 5×5     (F:36 B:37)

    static let allCourses: [GolfCourse] = {

        // Local helper: standard distribution for a given total par.
        func p(_ total: Int) -> [Int] {
            switch total {
            case 68: return [3,4,4,3,4,4,4,3,4, 4,3,4,4,4,4,4,4,4]
            case 69: return [3,4,3,4,5,3,4,4,3, 4,5,4,4,4,3,4,4,4]
            case 70: return [4,3,4,5,4,4,4,3,4, 4,4,3,5,4,4,4,3,4]
            case 71: return [4,3,5,4,4,4,3,4,5, 4,4,3,5,4,4,4,3,4]
            case 72: return [4,5,3,4,4,5,3,4,4, 4,5,3,4,4,5,3,4,4]
            case 73: return [4,5,3,4,5,4,4,3,4, 5,4,4,3,4,5,4,5,3]
            default: return Array(repeating: 4, count: 18)
            }
        }

        return [

        // ── United States – Top Public & Private ──────────────────────────

        // ★ Verified hole-by-hole
        GolfCourse(name: "Augusta National Golf Club", location: "Augusta, GA", country: "USA",
                   holePars: [4,5,4,3,4,3,4,5,4, 4,4,3,5,4,5,3,4,4]),   // Par 72
        // ★ Verified hole-by-hole
        GolfCourse(name: "Pebble Beach Golf Links", location: "Pebble Beach, CA", country: "USA",
                   holePars: [4,5,4,4,3,5,3,4,4, 4,4,3,4,5,4,4,3,5]),   // Par 72
        // ★ Verified hole-by-hole  (par 3s: 3,8,13,16 · par 5s: 4,10)
        GolfCourse(name: "Pinehurst No. 2", location: "Pinehurst, NC", country: "USA",
                   holePars: [4,4,3,5,4,4,4,3,4, 5,4,4,3,4,4,3,4,4]),   // Par 70
        GolfCourse(name: "Bethpage Black", location: "Farmingdale, NY", country: "USA",
                   holePars: p(71)),
        // ★ Verified hole-by-hole  (par 5s: 2,9,11,16 · par 3s: 3,8,12,17)
        GolfCourse(name: "TPC Sawgrass – Stadium Course", location: "Ponte Vedra Beach, FL", country: "USA",
                   holePars: [4,5,3,4,4,4,4,3,5, 4,5,3,4,4,4,5,3,4]),   // Par 72
        GolfCourse(name: "Torrey Pines South Course", location: "La Jolla, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Bandon Dunes", location: "Bandon, OR", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Bandon Trails", location: "Bandon, OR", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Pacific Dunes", location: "Bandon, OR", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Chambers Bay", location: "University Place, WA", country: "USA",
                   holePars: p(72)),
        // ★ Verified (2021 Ryder Cup scorecard – Kohler official)
        GolfCourse(name: "Whistling Straits", location: "Kohler, WI", country: "USA",
                   holePars: [4,5,3,4,5,4,3,4,4, 4,5,3,4,4,4,5,3,4]),   // Par 72
        GolfCourse(name: "Erin Hills", location: "Erin, WI", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Oakmont Country Club", location: "Oakmont, PA", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Winged Foot Golf Club", location: "Mamaroneck, NY", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Merion Golf Club", location: "Ardmore, PA", country: "USA",
                   holePars: p(70)),
        // ★ Verified (2018 US Open scorecard)
        GolfCourse(name: "Shinnecock Hills Golf Club", location: "Southampton, NY", country: "USA",
                   holePars: [4,3,4,4,5,4,3,4,4, 4,3,4,4,4,4,5,3,4]),   // Par 70
        GolfCourse(name: "Congressional Country Club", location: "Bethesda, MD", country: "USA",
                   holePars: p(70)),
        // ★ Verified (Genesis Invitational official hole-by-hole guide)
        GolfCourse(name: "Riviera Country Club", location: "Pacific Palisades, CA", country: "USA",
                   holePars: [5,4,4,3,4,3,4,4,4, 4,5,4,4,3,4,3,5,4]),   // Par 71
        GolfCourse(name: "Bay Hill Club & Lodge", location: "Orlando, FL", country: "USA",
                   holePars: p(72)),
        // ★ Verified (Sea Pines Resort official scorecard / RBC Heritage guide)
        GolfCourse(name: "Harbour Town Golf Links", location: "Hilton Head, SC", country: "USA",
                   holePars: [4,5,4,3,5,4,3,4,4, 4,4,4,4,3,5,4,3,4]),   // Par 71
        // ★ Verified (identical nines – 2021 PGA Championship scorecard)
        GolfCourse(name: "Kiawah Island Ocean Course", location: "Kiawah Island, SC", country: "USA",
                   holePars: [4,5,4,4,3,4,5,3,4, 4,5,4,4,3,4,5,3,4]),   // Par 72
        GolfCourse(name: "East Lake Golf Club", location: "Atlanta, GA", country: "USA",
                   holePars: p(72)),
        // ★ Verified (2022 PGA Championship scorecard – 5 par-3s, 4 par-5s, 9 par-4s)
        GolfCourse(name: "Southern Hills Country Club", location: "Tulsa, OK", country: "USA",
                   holePars: [4,5,3,4,5,3,4,3,4, 4,3,4,5,3,4,5,4,4]),   // Par 71
        GolfCourse(name: "Hazeltine National Golf Club", location: "Chaska, MN", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Medinah Country Club", location: "Medinah, IL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Baltusrol Golf Club", location: "Springfield, NJ", country: "USA",
                   holePars: p(70)),
        // ★ Verified (2025 PGA Championship scorecard)
        GolfCourse(name: "Quail Hollow Club", location: "Charlotte, NC", country: "USA",
                   holePars: [4,4,4,3,4,3,5,4,4, 5,4,4,3,4,5,4,3,4]),   // Par 71
        GolfCourse(name: "Colonial Country Club", location: "Fort Worth, TX", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Muirfield Village Golf Club", location: "Dublin, OH", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Firestone Country Club South", location: "Akron, OH", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Shadow Creek Golf Course", location: "North Las Vegas, NV", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Wolf Creek Golf Club", location: "Mesquite, NV", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Spyglass Hill Golf Course", location: "Pebble Beach, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Cypress Point Club", location: "Pebble Beach, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Pelican Hill Golf Club", location: "Newport Coast, CA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Torrey Pines North Course", location: "La Jolla, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "The Broadmoor East Course", location: "Colorado Springs, CO", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Arrowhead Golf Club", location: "Littleton, CO", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "TPC Colorado", location: "Berthoud, CO", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Streamsong Red", location: "Streamsong, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Streamsong Blue", location: "Streamsong, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "TPC Scottsdale Stadium Course", location: "Scottsdale, AZ", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Grayhawk Golf Club Raptor", location: "Scottsdale, AZ", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "We-Ko-Pa Golf Club Saguaro", location: "Fort McDowell, AZ", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Troon North Pinnacle Course", location: "Scottsdale, AZ", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Desert Highlands Golf Club", location: "Scottsdale, AZ", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Blackwolf Run River Course", location: "Kohler, WI", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Sand Valley Golf Course", location: "Nekoosa, WI", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Mammoth Dunes", location: "Nekoosa, WI", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Pinehurst No. 8", location: "Pinehurst, NC", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Mid Pines Inn & Golf Club", location: "Southern Pines, NC", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Pine Needles Lodge & Golf Club", location: "Southern Pines, NC", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Country Club of North Carolina Dogwood", location: "Pinehurst, NC", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Old Sandwich Golf Club", location: "Plymouth, MA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Cape Cod National Golf Club", location: "Brewster, MA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Atlantic Golf Club", location: "Bridgehampton, NY", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Sebonack Golf Club", location: "Southampton, NY", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Fishers Island Club", location: "Fishers Island, NY", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Garden City Golf Club", location: "Garden City, NY", country: "USA",
                   holePars: p(73)),
        GolfCourse(name: "Plainfield Country Club", location: "Plainfield, NJ", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Arcola Country Club", location: "Paramus, NJ", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Trump National Golf Club Bedminster", location: "Bedminster, NJ", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Trump National Golf Club Los Angeles", location: "Rancho Palos Verdes, CA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Prairie Dunes Country Club", location: "Hutchinson, KS", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Valhalla Golf Club", location: "Louisville, KY", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "TPC River Highlands", location: "Cromwell, CT", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Hartford Golf Club", location: "West Hartford, CT", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Augusta Country Club", location: "Augusta, GA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Sea Island Golf Club Seaside", location: "Sea Island, GA", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Reynolds Lake Oconee Great Waters", location: "Greensboro, GA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Calusa Pines Golf Club", location: "Naples, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Tiburón Golf Club Black Course", location: "Naples, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "TPC Tampa Bay", location: "Lutz, FL", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "World Woods Pine Barrens", location: "Brooksville, FL", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Mystic Dunes Golf Club", location: "Celebration, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "ChampionsGate International Course", location: "ChampionsGate, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Eagle Trace Golf Club", location: "Coral Springs, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Doral Blue Monster", location: "Miami, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Cowboys Golf Club", location: "Grapevine, TX", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "La Cantera Resort Golf Course", location: "San Antonio, TX", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Barton Creek Fazio Foothills", location: "Austin, TX", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Horseshoe Bay Resort Apple Rock", location: "Horseshoe Bay, TX", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Boot Ranch Golf Club", location: "Fredericksburg, TX", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "The Tribute Golf Club", location: "The Colony, TX", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "PGA Frisco East Course", location: "Frisco, TX", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "PGA Frisco West Course", location: "Frisco, TX", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Cog Hill Golf & Country Club Dubsdread", location: "Lemont, IL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Skokie Country Club", location: "Glencoe, IL", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Conway Farms Golf Club", location: "Lake Forest, IL", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Rich Harvest Farms", location: "Sugar Grove, IL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Eugene Country Club", location: "Eugene, OR", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Pumpkin Ridge Ghost Creek", location: "North Plains, OR", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Reserve Vineyards South Course", location: "Aloha, OR", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Sunriver Resort Crosswater", location: "Sunriver, OR", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Tetherow Golf Club", location: "Bend, OR", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Gamble Sands", location: "Brewster, WA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Suncadia Golf Resort Rope Rider", location: "Cle Elum, WA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Washington National Golf Club", location: "Auburn, WA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Salish Cliffs Golf Club", location: "Shelton, WA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Circling Raven Golf Club", location: "Worley, ID", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "The Reserve at Moonlight Basin", location: "Big Sky, MT", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Old Works Golf Course", location: "Anaconda, MT", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Boulders Resort South Course", location: "Carefree, AZ", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Talking Stick Golf Club North", location: "Scottsdale, AZ", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Coyote Lakes Golf Club", location: "Surprise, AZ", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Anthem Golf & Country Club", location: "Anthem, AZ", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Falcon Ridge Golf Club", location: "Mesquite, NV", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Red Rock Country Club", location: "Las Vegas, NV", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Las Vegas Paiute Golf Resort Sun Mountain", location: "Las Vegas, NV", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Cascata Golf Course", location: "Boulder City, NV", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Edgewood Tahoe Golf Course", location: "Stateline, NV", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Incline Village Championship Course", location: "Incline Village, NV", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Cabo Del Sol Ocean Course", location: "Cabo San Lucas, Mexico", country: "Mexico",
                   holePars: p(72)),

        // ── USA – Bay Area & Northern California ──────────────────────────
        GolfCourse(name: "TPC Harding Park", location: "San Francisco, CA", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Olympic Club Lake Course", location: "San Francisco, CA", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "California Golf Club of San Francisco", location: "South San Francisco, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Presidio Golf Course", location: "San Francisco, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Sharp Park Golf Course", location: "Pacifica, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Pasatiempo Golf Club", location: "Santa Cruz, CA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Half Moon Bay Golf Links Ocean Course", location: "Half Moon Bay, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Half Moon Bay Golf Links Old Course", location: "Half Moon Bay, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Links at Spanish Bay", location: "Pebble Beach, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Del Monte Golf Course", location: "Monterey, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Poppy Hills Golf Course", location: "Pebble Beach, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Pebble Beach Monterey Peninsula Shore Course", location: "Pebble Beach, CA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "CordeValle Golf Club", location: "San Martin, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Cinnabar Hills Golf Club", location: "San Jose, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Coyote Creek Golf Club Tournament Course", location: "San Jose, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Poppy Ridge Golf Course", location: "Livermore, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "The Course at Wente Vineyards", location: "Livermore, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Boundary Oak Golf Course", location: "Walnut Creek, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Tilden Park Golf Course", location: "Berkeley, CA", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Lake Chabot Golf Course", location: "Oakland, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Crystal Springs Golf Course", location: "Burlingame, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Sequoyah Country Club", location: "Oakland, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Claremont Country Club", location: "Oakland, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Diablo Country Club", location: "Diablo, CA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Round Hill Country Club", location: "Alamo, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Crow Canyon Country Club", location: "Danville, CA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "San Ramon Golf Club", location: "San Ramon, CA", country: "USA",
                   holePars: p(71)),

        // ── USA – Southern California ──────────────────────────────────────
        GolfCourse(name: "Los Angeles Country Club North Course", location: "Los Angeles, CA", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Los Angeles Country Club South Course", location: "Los Angeles, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Bel-Air Country Club", location: "Los Angeles, CA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Wilshire Country Club", location: "Los Angeles, CA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Lakeside Golf Club", location: "Burbank, CA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "La Jolla Country Club", location: "La Jolla, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Aviara Golf Club", location: "Carlsbad, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Barona Creek Golf Club", location: "Lakeside, CA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "El Caballero Country Club", location: "Tarzana, CA", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Palos Verdes Golf Club", location: "Palos Verdes Estates, CA", country: "USA",
                   holePars: p(71)),

        // ── USA – More TPC Venues ──────────────────────────────────────────
        GolfCourse(name: "TPC Deere Run", location: "Silvis, IL", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "TPC Twin Cities", location: "Blaine, MN", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "TPC Boston", location: "Norton, MA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "TPC San Antonio AT&T Oaks Course", location: "San Antonio, TX", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "TPC Las Vegas", location: "Las Vegas, NV", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "TPC Southwind", location: "Memphis, TN", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "TPC Sugarloaf", location: "Duluth, GA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "TPC Louisiana", location: "Avondale, LA", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "TPC Craig Ranch", location: "McKinney, TX", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "TPC Potomac at Avenel Farm", location: "Potomac, MD", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "TPC Stonebrae", location: "Hayward, CA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "TPC Piper Glen", location: "Charlotte, NC", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "TPC Sawgrass Valley Course", location: "Ponte Vedra Beach, FL", country: "USA",
                   holePars: p(71)),

        // ── USA – Northeast ────────────────────────────────────────────────
        GolfCourse(name: "Oak Hill Country Club East Course", location: "Pittsford, NY", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Ridgewood Country Club", location: "Paramus, NJ", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Aronimink Golf Club", location: "Newtown Square, PA", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Wilmington Country Club South Course", location: "Wilmington, DE", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Bethpage Red Course", location: "Farmingdale, NY", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Bethpage Yellow Course", location: "Farmingdale, NY", country: "USA",
                   holePars: p(71)),

        // ── USA – Mid-Atlantic & Southeast ─────────────────────────────────
        GolfCourse(name: "Caves Valley Golf Club", location: "Owings Mills, MD", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "The Greenbrier Old White TPC", location: "White Sulphur Springs, WV", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Sedgefield Country Club", location: "Greensboro, NC", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Pinehurst No. 4", location: "Pinehurst, NC", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Pinehurst No. 7", location: "Pinehurst, NC", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Pinehurst No. 9", location: "Pinehurst, NC", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Atlanta Athletic Club Highlands Course", location: "Johns Creek, GA", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Peachtree Golf Club", location: "Atlanta, GA", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Champions Golf Club Cypress Creek", location: "Houston, TX", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Memorial Park Golf Course", location: "Houston, TX", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Innisbrook Resort Copperhead Course", location: "Palm Harbor, FL", country: "USA",
                   holePars: p(71)),
        GolfCourse(name: "Seminole Golf Club", location: "Juno Beach, FL", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "The Medalist Golf Club", location: "Hobe Sound, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Bear's Club", location: "Jupiter, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Streamsong Black", location: "Streamsong, FL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Hammock Dunes Tom Fazio Course", location: "Palm Coast, FL", country: "USA",
                   holePars: p(72)),

        // ── USA – Midwest & Mountain ───────────────────────────────────────
        GolfCourse(name: "Cantigny Golf Woodside Course", location: "Wheaton, IL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Butler National Golf Club", location: "Oak Brook, IL", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Chicago Golf Club", location: "Wheaton, IL", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Olympia Fields Country Club North Course", location: "Olympia Fields, IL", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Interlachen Country Club", location: "Edina, MN", country: "USA",
                   holePars: p(72)),
        GolfCourse(name: "Oakland Hills Country Club South Course", location: "Bloomfield Hills, MI", country: "USA",
                   holePars: p(70)),
        GolfCourse(name: "Detroit Golf Club", location: "Detroit, MI", country: "USA",
                   holePars: p(71)),

        // ── UK & Ireland ──────────────────────────────────────────────────
        // ★ Verified hole-by-hole  (par 5s: 5,14 · par 3s: 8,11)
        GolfCourse(name: "The Old Course at St Andrews", location: "St Andrews, Fife", country: "Scotland",
                   holePars: [4,4,4,4,5,4,4,3,4, 4,3,4,4,5,4,4,4,4]),   // Par 72
        GolfCourse(name: "St Andrews New Course", location: "St Andrews, Fife", country: "Scotland",
                   holePars: p(71)),
        GolfCourse(name: "St Andrews Castle Course", location: "St Andrews, Fife", country: "Scotland",
                   holePars: p(73)),
        GolfCourse(name: "St Andrews Jubilee Course", location: "St Andrews, Fife", country: "Scotland",
                   holePars: p(72)),
        // ★ Verified (The Open Championship official scorecard · par-5s: 6,14 · par-3s: 8,13,15)
        GolfCourse(name: "Carnoustie Golf Links Championship", location: "Carnoustie, Angus", country: "Scotland",
                   holePars: [4,4,4,4,4,5,4,3,4, 4,4,4,3,5,3,4,4,4]),   // Par 71
        // ★ Verified (2024 Open Championship layout · "Postage Stamp" H8 par-3 · par-5s: 4,6,16 · par-3s: 5,8,14,17)
        GolfCourse(name: "Royal Troon Old Course", location: "Troon, Ayrshire", country: "Scotland",
                   holePars: [4,4,4,5,3,5,4,3,4, 4,4,4,4,3,4,5,3,4]),   // Par 71
        GolfCourse(name: "Turnberry Ailsa Course", location: "Turnberry, Ayrshire", country: "Scotland",
                   holePars: p(71)),
        // ★ Verified (The Honourable Company · clockwise/counter-clockwise routing · par-5s: 5,9,17 · par-3s: 4,7,13,16)
        GolfCourse(name: "Muirfield", location: "Gullane, East Lothian", country: "Scotland",
                   holePars: [4,4,4,3,5,4,3,4,5, 4,4,4,3,4,4,3,5,4]),   // Par 71
        GolfCourse(name: "Royal Dornoch Championship Course", location: "Dornoch, Sutherland", country: "Scotland",
                   holePars: p(70)),
        GolfCourse(name: "Kingsbarns Golf Links", location: "St Andrews, Fife", country: "Scotland",
                   holePars: p(72)),
        GolfCourse(name: "Dumbarnie Links", location: "Leven, Fife", country: "Scotland",
                   holePars: p(72)),
        GolfCourse(name: "Machrihanish Dunes", location: "Machrihanish, Argyll", country: "Scotland",
                   holePars: p(72)),
        GolfCourse(name: "Gleneagles King's Course", location: "Auchterarder, Perthshire", country: "Scotland",
                   holePars: p(70)),
        GolfCourse(name: "Gleneagles Queen's Course", location: "Auchterarder, Perthshire", country: "Scotland",
                   holePars: p(68)),
        GolfCourse(name: "North Berwick West Links", location: "North Berwick, East Lothian", country: "Scotland",
                   holePars: p(71)),
        GolfCourse(name: "Cruden Bay Golf Club", location: "Cruden Bay, Aberdeenshire", country: "Scotland",
                   holePars: p(70)),
        GolfCourse(name: "Prestwick Golf Club", location: "Prestwick, Ayrshire", country: "Scotland",
                   holePars: p(73)),
        GolfCourse(name: "Western Gailes Golf Club", location: "Irvine, Ayrshire", country: "Scotland",
                   holePars: p(71)),
        GolfCourse(name: "Royal Aberdeen Golf Club Balgownie Links", location: "Aberdeen, Aberdeenshire", country: "Scotland",
                   holePars: p(71)),
        GolfCourse(name: "Nairn Golf Club", location: "Nairn, Inverness-shire", country: "Scotland",
                   holePars: p(70)),
        GolfCourse(name: "Brora Golf Club", location: "Brora, Sutherland", country: "Scotland",
                   holePars: p(70)),
        GolfCourse(name: "Golspie Golf Club", location: "Golspie, Sutherland", country: "Scotland",
                   holePars: p(68)),
        GolfCourse(name: "Trump International Golf Links Scotland", location: "Balmedie, Aberdeenshire", country: "Scotland",
                   holePars: p(72)),
        GolfCourse(name: "Renaissance Club", location: "North Berwick, East Lothian", country: "Scotland",
                   holePars: p(71)),
        GolfCourse(name: "Archerfield Links Fidra Course", location: "North Berwick, East Lothian", country: "Scotland",
                   holePars: p(72)),
        GolfCourse(name: "Royal Birkdale Golf Club", location: "Southport, Lancashire", country: "England",
                   holePars: p(70)),
        // ★ Verified (2021 Open Championship scorecard · par-5s: 7,14 · par-3s: 3,6,11,16)
        GolfCourse(name: "Royal St George's Golf Club", location: "Sandwich, Kent", country: "England",
                   holePars: [4,4,3,4,4,3,5,4,4, 4,3,4,4,5,4,3,4,4]),   // Par 70
        GolfCourse(name: "Royal Lytham & St Annes Golf Club", location: "St Annes-on-Sea, Lancashire", country: "England",
                   holePars: p(70)),
        GolfCourse(name: "Royal Liverpool Golf Club", location: "Hoylake, Merseyside", country: "England",
                   holePars: p(72)),
        GolfCourse(name: "The Belfry Brabazon Course", location: "Sutton Coldfield, West Midlands", country: "England",
                   holePars: p(72)),
        GolfCourse(name: "Wentworth Club West Course", location: "Virginia Water, Surrey", country: "England",
                   holePars: p(72)),
        GolfCourse(name: "Wentworth Club East Course", location: "Virginia Water, Surrey", country: "England",
                   holePars: p(72)),
        GolfCourse(name: "Sunningdale Old Course", location: "Sunningdale, Berkshire", country: "England",
                   holePars: p(70)),
        GolfCourse(name: "Walton Heath Golf Club Old Course", location: "Tadworth, Surrey", country: "England",
                   holePars: p(72)),
        GolfCourse(name: "Hillside Golf Club", location: "Southport, Lancashire", country: "England",
                   holePars: p(72)),
        GolfCourse(name: "Southport & Ainsdale Golf Club", location: "Southport, Lancashire", country: "England",
                   holePars: p(72)),
        GolfCourse(name: "Ganton Golf Club", location: "Ganton, North Yorkshire", country: "England",
                   holePars: p(72)),
        GolfCourse(name: "Royal North Devon Golf Club", location: "Westward Ho!, Devon", country: "England",
                   holePars: p(71)),
        GolfCourse(name: "Swinley Forest Golf Club", location: "Ascot, Berkshire", country: "England",
                   holePars: p(68)),
        GolfCourse(name: "Royal Wimbledon Golf Club", location: "Wimbledon, London", country: "England",
                   holePars: p(70)),
        GolfCourse(name: "Portmarnock Golf Club", location: "Portmarnock, Co. Dublin", country: "Ireland",
                   holePars: p(72)),
        // ★ Verified (Royal County Down official scorecard · par-5s: 1,12,18 · par-3s: 4,7,10,14)
        GolfCourse(name: "Royal County Down Championship Course", location: "Newcastle, Co. Down", country: "N. Ireland",
                   holePars: [5,4,4,3,4,4,3,4,4, 3,4,5,4,3,4,4,4,5]),   // Par 71
        // ★ Verified (2019 & 2025 Open Championship scorecard · par-5s: 2,7,12 · par-3s: 3,6,13,16)
        GolfCourse(name: "Royal Portrush Dunluce Links", location: "Portrush, Co. Antrim", country: "N. Ireland",
                   holePars: [4,5,3,4,4,3,5,4,4, 4,4,5,3,4,4,3,4,4]),   // Par 71
        GolfCourse(name: "Ballybunion Old Course", location: "Ballybunion, Co. Kerry", country: "Ireland",
                   holePars: p(71)),
        GolfCourse(name: "Lahinch Golf Club Old Course", location: "Lahinch, Co. Clare", country: "Ireland",
                   holePars: p(72)),
        GolfCourse(name: "Waterville Golf Links", location: "Waterville, Co. Kerry", country: "Ireland",
                   holePars: p(72)),
        GolfCourse(name: "Adare Manor Golf Course", location: "Adare, Co. Limerick", country: "Ireland",
                   holePars: p(72)),
        GolfCourse(name: "The European Club", location: "Brittas Bay, Co. Wicklow", country: "Ireland",
                   holePars: p(71)),
        GolfCourse(name: "Doonbeg Golf Club", location: "Doonbeg, Co. Clare", country: "Ireland",
                   holePars: p(72)),
        GolfCourse(name: "Old Head Golf Links", location: "Kinsale, Co. Cork", country: "Ireland",
                   holePars: p(72)),
        GolfCourse(name: "Rosapenna Sandy Hills Links", location: "Rosapenna, Co. Donegal", country: "Ireland",
                   holePars: p(71)),
        GolfCourse(name: "Carne Golf Links", location: "Belmullet, Co. Mayo", country: "Ireland",
                   holePars: p(73)),
        GolfCourse(name: "Dooks Golf Club", location: "Glenbeigh, Co. Kerry", country: "Ireland",
                   holePars: p(70)),
        GolfCourse(name: "Tralee Golf Club", location: "Tralee, Co. Kerry", country: "Ireland",
                   holePars: p(71)),
        GolfCourse(name: "Slieve Russell Hotel Golf Club", location: "Ballyconnell, Co. Cavan", country: "Ireland",
                   holePars: p(72)),
        GolfCourse(name: "Druids Glen Golf Club", location: "Newtownmountkennedy, Co. Wicklow", country: "Ireland",
                   holePars: p(71)),
        GolfCourse(name: "Luttrellstown Castle Golf Club", location: "Clonsilla, Co. Dublin", country: "Ireland",
                   holePars: p(72)),
        GolfCourse(name: "The KN Golf Links Kenmare", location: "Kenmare, Co. Kerry", country: "Ireland",
                   holePars: p(70)),

        // ── Australia & New Zealand ────────────────────────────────────────
        GolfCourse(name: "Royal Melbourne West Course", location: "Melbourne, VIC", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "Royal Melbourne East Course", location: "Melbourne, VIC", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "Kingston Heath Golf Club", location: "Melbourne, VIC", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "Metropolitan Golf Club", location: "Melbourne, VIC", country: "Australia",
                   holePars: p(70)),
        GolfCourse(name: "Victoria Golf Club", location: "Melbourne, VIC", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "National Golf Club Cape Schanck", location: "Cape Schanck, VIC", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "Ellerston Golf Course", location: "Upper Hunter Valley, NSW", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "Royal Sydney Golf Club", location: "Sydney, NSW", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "New South Wales Golf Club", location: "La Perouse, NSW", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "Royal Adelaide Golf Club", location: "Adelaide, SA", country: "Australia",
                   holePars: p(73)),
        GolfCourse(name: "Kooyonga Golf Club", location: "Adelaide, SA", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "Royal Queensland Golf Club", location: "Brisbane, QLD", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "Barnbougle Dunes", location: "Bridport, TAS", country: "Australia",
                   holePars: p(71)),
        GolfCourse(name: "Barnbougle Lost Farm", location: "Bridport, TAS", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "Cape Wickham Links", location: "King Island, TAS", country: "Australia",
                   holePars: p(72)),
        GolfCourse(name: "Paraparaumu Beach Golf Club", location: "Paraparaumu, Wellington", country: "New Zealand",
                   holePars: p(71)),
        GolfCourse(name: "Tara Iti Golf Club", location: "Te Arai, Auckland", country: "New Zealand",
                   holePars: p(72)),
        GolfCourse(name: "The Hills Golf Club", location: "Arrowtown, Queenstown", country: "New Zealand",
                   holePars: p(72)),

        // ── Europe ─────────────────────────────────────────────────────────
        GolfCourse(name: "Real Club Valderrama", location: "Sotogrande, Cádiz", country: "Spain",
                   holePars: p(71)),
        GolfCourse(name: "Real Club de Golf Sotogrande", location: "Sotogrande, Cádiz", country: "Spain",
                   holePars: p(72)),
        GolfCourse(name: "Circuito de Málaga Finca Cortesín", location: "Casares, Málaga", country: "Spain",
                   holePars: p(72)),
        GolfCourse(name: "PGA Catalunya Stadium Course", location: "Caldes de Malavella, Girona", country: "Spain",
                   holePars: p(72)),
        GolfCourse(name: "Real Club de Golf El Prat", location: "Terrassa, Barcelona", country: "Spain",
                   holePars: p(72)),
        GolfCourse(name: "Golf du Médoc Les Châteaux", location: "Le Pian-Médoc, Bordeaux", country: "France",
                   holePars: p(71)),
        GolfCourse(name: "Golf National Albatros Course", location: "Saint-Quentin-en-Yvelines", country: "France",
                   holePars: p(72)),
        GolfCourse(name: "Golf Evian Resort", location: "Évian-les-Bains, Haute-Savoie", country: "France",
                   holePars: p(71)),
        GolfCourse(name: "Golf Club Crans-sur-Sierre", location: "Crans-Montana, Valais", country: "Switzerland",
                   holePars: p(71)),
        GolfCourse(name: "Golf Club Milano", location: "Monza, Lombardy", country: "Italy",
                   holePars: p(72)),
        GolfCourse(name: "Muravera Golf Club", location: "Muravera, Sardinia", country: "Italy",
                   holePars: p(72)),
        GolfCourse(name: "Quellness Golf Resort Bad Griesbach Uttlau", location: "Bad Griesbach, Bavaria", country: "Germany",
                   holePars: p(72)),
        GolfCourse(name: "GC Eichenried", location: "Eichenried, Bavaria", country: "Germany",
                   holePars: p(72)),
        GolfCourse(name: "Hamburger Golf-Club Falkenstein", location: "Hamburg", country: "Germany",
                   holePars: p(72)),
        GolfCourse(name: "Diamond Country Club Atzenbrugg", location: "Atzenbrugg, Lower Austria", country: "Austria",
                   holePars: p(72)),
        GolfCourse(name: "Gut Altentann Golf Resort", location: "Henndorf am Wallersee, Salzburg", country: "Austria",
                   holePars: p(72)),

        // ── Asia & Middle East ─────────────────────────────────────────────
        GolfCourse(name: "Mission Hills Hainan Blackstone Course", location: "Haikou, Hainan", country: "China",
                   holePars: p(72)),
        GolfCourse(name: "Mission Hills Hainan World No. 1 Course", location: "Haikou, Hainan", country: "China",
                   holePars: p(72)),
        GolfCourse(name: "Sheshan International Golf Club", location: "Shanghai", country: "China",
                   holePars: p(72)),
        GolfCourse(name: "Fanling New Course", location: "Fanling, New Territories", country: "Hong Kong",
                   holePars: p(70)),
        GolfCourse(name: "Sentosa Golf Club Serapong Course", location: "Sentosa Island", country: "Singapore",
                   holePars: p(72)),
        GolfCourse(name: "Nirwana Bali Golf Club", location: "Tabanan, Bali", country: "Indonesia",
                   holePars: p(72)),
        GolfCourse(name: "Ria Bintan Golf Club Ocean Course", location: "Bintan Island", country: "Indonesia",
                   holePars: p(72)),
        GolfCourse(name: "Sky72 Golf & Resort Ocean Course", location: "Incheon", country: "South Korea",
                   holePars: p(72)),
        GolfCourse(name: "Nine Bridges Golf Club", location: "Jeju Island", country: "South Korea",
                   holePars: p(72)),
        GolfCourse(name: "Kasumigaseki Country Club East Course", location: "Kawagoe, Saitama", country: "Japan",
                   holePars: p(72)),
        GolfCourse(name: "Naruo Golf Club", location: "Amagasaki, Hyogo", country: "Japan",
                   holePars: p(72)),
        GolfCourse(name: "Earth Mahoroba Golf Club", location: "Hokkaido", country: "Japan",
                   holePars: p(72)),
        GolfCourse(name: "Hirono Golf Club", location: "Miki, Hyogo", country: "Japan",
                   holePars: p(72)),
        GolfCourse(name: "Kawana Hotel Fuji Course", location: "Ito, Shizuoka", country: "Japan",
                   holePars: p(72)),
        GolfCourse(name: "Taiheiyo Club Gotemba Course", location: "Gotemba, Shizuoka", country: "Japan",
                   holePars: p(72)),
        GolfCourse(name: "Emirates Golf Club Majlis Course", location: "Dubai", country: "UAE",
                   holePars: p(72)),
        GolfCourse(name: "Yas Links Abu Dhabi", location: "Yas Island, Abu Dhabi", country: "UAE",
                   holePars: p(72)),
        GolfCourse(name: "Trump International Golf Club Dubai", location: "DAMAC Hills, Dubai", country: "UAE",
                   holePars: p(71)),
        GolfCourse(name: "The Els Club Dubai", location: "Sports City, Dubai", country: "UAE",
                   holePars: p(72)),
        GolfCourse(name: "Al Mouj Golf", location: "Muscat", country: "Oman",
                   holePars: p(72)),
        GolfCourse(name: "Royal Greens Golf & Country Club", location: "King Abdullah Economic City", country: "Saudi Arabia",
                   holePars: p(72)),
        GolfCourse(name: "Royal Dar Es Salam Red Course", location: "Rabat", country: "Morocco",
                   holePars: p(73)),
        GolfCourse(name: "Laguna Lang Co Golf Club", location: "Lang Co, Hue Province", country: "Vietnam",
                   holePars: p(71)),
        GolfCourse(name: "Bluewater Maribago Golf Course", location: "Mactan Island, Cebu", country: "Philippines",
                   holePars: p(72)),

        // ── South Africa ───────────────────────────────────────────────────
        GolfCourse(name: "Leopard Creek Country Club", location: "Malelane, Mpumalanga", country: "South Africa",
                   holePars: p(72)),
        GolfCourse(name: "Lost City Golf Course", location: "Sun City, North West", country: "South Africa",
                   holePars: p(72)),
        GolfCourse(name: "Fancourt Montagu Course", location: "George, Western Cape", country: "South Africa",
                   holePars: p(72)),
        GolfCourse(name: "Royal Cape Golf Club", location: "Cape Town, Western Cape", country: "South Africa",
                   holePars: p(72)),
        GolfCourse(name: "Durban Country Club", location: "Durban, KwaZulu-Natal", country: "South Africa",
                   holePars: p(72)),
        GolfCourse(name: "Glendower Golf Club", location: "Johannesburg, Gauteng", country: "South Africa",
                   holePars: p(72)),
        GolfCourse(name: "Blair Atholl Golf & Equestrian Estate", location: "Johannesburg, Gauteng", country: "South Africa",
                   holePars: p(72)),

        // ── Canada – Original ──────────────────────────────────────────────
        GolfCourse(name: "St. George's Golf & Country Club", location: "Etobicoke, ON", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Hamilton Golf & Country Club", location: "Ancaster, ON", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Capilano Golf & Country Club", location: "West Vancouver, BC", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Cabot Links", location: "Inverness, NS", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Cabot Cliffs", location: "Inverness, NS", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Banff Springs Golf Course", location: "Banff, AB", country: "Canada",
                   holePars: p(71)),
        GolfCourse(name: "Jasper Park Lodge Golf Course", location: "Jasper, AB", country: "Canada",
                   holePars: p(71)),
        GolfCourse(name: "Greywolf Golf Course", location: "Panorama, BC", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "The Ridge at Manitou", location: "Minett, ON", country: "Canada",
                   holePars: p(72)),

        // ── Canada – Ontario (expanded) ────────────────────────────────────
        GolfCourse(name: "Flemingdon Park Golf Club", location: "Toronto, ON", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Glen Abbey Golf Club", location: "Oakville, ON", country: "Canada",
                   holePars: p(73)),
        GolfCourse(name: "Angus Glen Golf Club South Course", location: "Markham, ON", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Angus Glen Golf Club North Course", location: "Markham, ON", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Eagles Nest Golf Club", location: "Maple, ON", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Lionhead Golf Club Legends Course", location: "Brampton, ON", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "National Golf Club of Canada", location: "Woodbridge, ON", country: "Canada",
                   holePars: p(71)),
        GolfCourse(name: "Beacon Hall Golf Club", location: "Aurora, ON", country: "Canada",
                   holePars: p(71)),
        GolfCourse(name: "Rosedale Golf Club", location: "Toronto, ON", country: "Canada",
                   holePars: p(71)),
        GolfCourse(name: "Toronto Golf Club", location: "Mississauga, ON", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Islington Golf Club", location: "Toronto, ON", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Weston Golf & Country Club", location: "Toronto, ON", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Humber Valley Golf Course", location: "Toronto, ON", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Scarlett Woods Golf Course", location: "Toronto, ON", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Dentonia Park Golf Course", location: "Toronto, ON", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Don Valley Golf Course", location: "Toronto, ON", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Cedar Brae Golf & Country Club", location: "Toronto, ON", country: "Canada",
                   holePars: p(71)),
        GolfCourse(name: "TPC Toronto at Osprey Valley Heathlands", location: "Caledon, ON", country: "Canada",
                   holePars: p(71)),
        GolfCourse(name: "TPC Toronto at Osprey Valley North", location: "Caledon, ON", country: "Canada",
                   holePars: p(72)),

        // ── Canada – British Columbia ───────────────────────────────────────
        GolfCourse(name: "Point Grey Golf & Country Club", location: "Vancouver, BC", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Marine Drive Golf Club", location: "Vancouver, BC", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Shaughnessy Golf & Country Club", location: "Vancouver, BC", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "University Golf Club", location: "Vancouver, BC", country: "Canada",
                   holePars: p(71)),
        GolfCourse(name: "Langara Golf Course", location: "Vancouver, BC", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Victoria Golf Club", location: "Victoria, BC", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Royal Colwood Golf Club", location: "Victoria, BC", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Gallagher's Canyon Golf Club", location: "Kelowna, BC", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Predator Ridge Golf Resort Ridge Course", location: "Vernon, BC", country: "Canada",
                   holePars: p(72)),

        // ── Canada – Alberta & Prairies ─────────────────────────────────────
        GolfCourse(name: "Redwood Meadows Golf & Country Club", location: "Calgary, AB", country: "Canada",
                   holePars: p(72)),
        GolfCourse(name: "Wolf Creek Golf Resort", location: "Ponoka, AB", country: "Canada",
                   holePars: p(70)),
        GolfCourse(name: "Royal Mayfair Golf Club", location: "Edmonton, AB", country: "Canada",
                   holePars: p(71)),
        GolfCourse(name: "Lynx Ridge Golf Club", location: "Calgary, AB", country: "Canada",
                   holePars: p(71)),
        GolfCourse(name: "Priddis Greens Golf & Country Club", location: "Priddis, AB", country: "Canada",
                   holePars: p(72)),

        ] // end return
    }() // end closure

    // MARK: - Search

    static func search(_ query: String) -> [GolfCourse] {
        let trimmed = query.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { return allCourses }
        return allCourses.filter {
            $0.name.localizedCaseInsensitiveContains(trimmed) ||
            $0.location.localizedCaseInsensitiveContains(trimmed) ||
            $0.country.localizedCaseInsensitiveContains(trimmed)
        }
    }

    static var courseNames: [String] {
        allCourses.map { $0.name }
    }
}
